#ifndef __ISR_H__
#define __ISR_H__

void isrDivideZero();
void isrDebugMode();
void isrNMI();
void isrINT3();
void isrOverflow();
void isrOverAddress();
void isrNonExistCommand();
void isrNonExistDevice();
void isrContinuousException();
void isrCoprocessorError();
void isrTSSError();
void isrOverSegment();
void isrStackSegmentError();
void isrViolidProtectRule();
void isrPageFault();
void isrNonDefiled();
void isrFloatingError();
void isrAligndError();
void isrMachineCheckError();
void isrSIMDError();
void isrVirtualizationError();
void isrControlProtectionException();
void isrDefault22();
void isrDefault23();
void isrDefault24();
void isrDefault25();
void isrDefault26();
void isrDefault27();
void isrDefault28();
void isrDefault29();
void isrDefault31();
void isrDefault();
void isrSecurityError();
void isrTimerInterrupt();
void isrKeyboardInterrupt();
void isrMouseInterrupt();

#endif /*__ISR_H__*/
